version: '3.9'
services:
  adminer:
    image: adminer
    #restart: unless-stopped
    container_name: db-adminer
    networks:
      - net-db
    ports:
      - 9081:8080
  
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    #restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: huynhquocbuu@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    volumes:
       - ./pgadmin4-data:/var/lib/pgadmin
    ports:
      - 9082:80
    networks:
      - net-db
  
  mysqldb:
    image: mysql
    #restart: unless-stopped
    container_name: mysqldb
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - net-db
    ports:
      - 3306:3306

  mariadb:
    image: mariadb
    #restart: unless-stopped
    container_name: mariadb
    volumes:
      - ./maria-data:/var/lib/mysql
    environment: 
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - net-db
    ports:
      - 3308:3306

  postgresdb:
    image: postgres
    #restart: unless-stopped
    container_name: postgresdb
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data/data:/var/lib/postgresql/data
    networks:
      - net-db
    ports:
      - 5432:5432

networks:
  net-db:
    name: net-db
    driver: bridge
  net-elk:
    name: net-elk
    driver: bridge
  net-message-queue:
    name: net-message-queue
    driver: bridge
  net-app:
    name: net-app
    driver: bridge