version: '3.9'
services:  
  mssqldb:
    image: mcr.microsoft.com/mssql/server
    #restart: unless-stopped
    container_name: mssqldb
    #hostname: mssqldb
    environment:
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: Y
    volumes:
      - ./mssql-data:/var/opt/mssql
      #- ./mssql-data/log:/var/opt/mssql/log
    networks:
      - net-db
    ports:
      - 1433:1433

networks:
  net-db:
    name: net-db
    driver: bridge
  net-elk:
    name: net-elk
    driver: bridge
  net-message-queue:
    name: net-message-queue
    driver: bridge
  net-app:
    name: net-app
    driver: bridge