version: '3.9'
services:
  azure-sql-edge:
    image: mcr.microsoft.com/azure-sql-edge
    #restart: unless-stopped
    container_name: mssqldb
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: Y
    volumes:
      - ./azure-sql-edge/data:/var/opt/mssql/data
      - ./azure-sql-edge/log:/var/opt/mssql/log
    networks:
      - net-db
    ports:
      - 1433:1433

networks:
  net-db:
    name: net-db
    driver: bridge
  net-elk:
    name: net-elk
    driver: bridge
  net-message-queue:
    name: net-message-queue
    driver: bridge
  net-app:
    name: net-app
    driver: bridge