version: '3.9'
services:
  
  keycloak:
    image: jboss/keycloak
    #restart: unless-stopped
    depends_on:
      - postgresdb
    container_name: jboss_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgresdb
      DB_DATABASE: ${KEYCLOAK_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - 9086:8080
      - 8787:8787
    volumes:
        - ./keycloak/import:/temp
        - ./keycloak/themes:/opt/jboss/keycloak/themes
    networks:
      - net-db

networks:
  net-db:
    name: net-db
    driver: bridge
  net-elk:
    name: net-elk
    driver: bridge
  net-message-queue:
    name: net-message-queue
    driver: bridge
  net-app:
    name: net-app
    driver: bridge