version: '3.6'

services:
  elasticsearch:
    container_name: els
    #image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0-arm64
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment: 
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - discovery.type=single-node
    #restart: always
    networks:
      - elastic
  kibana:
    container_name: kibana
    #image: docker.elastic.co/kibana/kibana:8.7.0-arm64
    image: docker.elastic.co/kibana/kibana:8.7.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    #restart: always
    networks:
      - elastic

  wiremock:
    container_name: wiremock
    image: wiremock/wiremock
    ports:
      - 9880:8080
    volumes:
      - wiremock-data:/home/wiremock
    depends_on:
      - elasticsearch
    #restart: always
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./elasticsearch-data
  wiremock-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./wiremock-data