version: '3.9'
services:
  wiremock:
    container_name: wiremock
    image: wiremock/wiremock
    ports:
      - 9081:8080
    volumes:
      - ./wiremock-data:/home/wiremock
    networks:
      - net-app

networks:
  net-db:
    name: net-db
    driver: bridge
  net-elk:
    name: net-elk
    driver: bridge
  net-message-queue:
    name: net-message-queue
    driver: bridge
  net-app:
    name: net-app
    driver: bridge